updated cloud init script

diff --git a/standalone-node/hook_os/files/cloud-init.yaml b/standalone-node/hook_os/files/cloud-init.yaml
--- a/standalone-node/hook_os/files/cloud-init.yaml
+++ b/standalone-node/hook_os/files/cloud-init.yaml
@@ -42,3 +42,24 @@ runcmd:
        chmod +x rke2-setup-post-reboot.sh
        bash rke2-setup-post-reboot.sh
     fi
+
+    # Verify system boot status
+    bootctl_output=$(sudo bootctl list)
+
+    # Check if linux-2.efi is selected
+    # Make the updated image persistent for future boots
+    if echo "$bootctl_output" | grep -q "(linux-2.efi) (selected)"; then
+        echo "linux-2.efi is selected. Performing commit."
+        if os-update-tool.sh -c; then
+            echo "Commit update successful."
+        else
+            echo "Failed to commit update."
+            exit 1
+        fi
+    else
+        echo "linux-2.efi is not selected. Skipping commit."
+    fi
+
+    # Fetch and echo IMAGE_BUILD_DATE from /etc/image-id
+    IMAGE_BUILD_DATE=$(grep '^IMAGE_BUILD_DATE=' /etc/image-id | cut -d '=' -f2)
+    echo "IMAGE_BUILD_DATE: $IMAGE_BUILD_DATE"
